{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2020-4161"
    },
    "affects": {
      "vendor": {
        "vendor_data": []
      }
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "IBM DB2 for Linux, UNIX and Windows (includes DB2 Connect Server) 11.5 could allow an authenticated attacker to cause a denial of service due to incorrect handling of certain commands. IBM X-Force ID: 174341."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "ibm-db2-cve20204161-dos (174341)",
          "refsource": "XF",
          "tags": [],
          "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/174341"
        },
        {
          "name": "https://www.ibm.com/support/pages/node/2874621",
          "refsource": "CONFIRM",
          "tags": [],
          "url": "https://www.ibm.com/support/pages/node/2874621"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2020-02-19T16:24Z",
  "publishedDate": "2020-02-19T16:15Z"
}