{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "cpe_match": [
          {
            "cpe23Uri": "cpe:2.3:a:ibm:cognos_analytics:11.0.0:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:ibm:cognos_analytics:11.1.0:*:*:*:*:*:*:*",
            "vulnerable": true
          }
        ],
        "operator": "OR"
      }
    ]
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2019-4343"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "product": {
              "product_data": [
                {
                  "product_name": "cognos_analytics",
                  "version": {
                    "version_data": [
                      {
                        "version_affected": "=",
                        "version_value": "11.0.0"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "11.1.0"
                      }
                    ]
                  }
                }
              ]
            },
            "vendor_name": "ibm"
          }
        ]
      }
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "IBM Cognos Analytics 11.0 and 11.1 allows overly permissive cross-origin resource sharing which could allow an attacker to transfer private information. An attacker could exploit this vulnerability to access content that should be restricted. IBM X-Force ID: 161422."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-200"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "ibm-cognos-cve20194343-cors (161422)",
          "refsource": "XF",
          "tags": [
            "VDB Entry",
            "Vendor Advisory"
          ],
          "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/161422"
        },
        {
          "name": "https://www.ibm.com/support/pages/node/1146424",
          "refsource": "CONFIRM",
          "tags": [
            "Vendor Advisory"
          ],
          "url": "https://www.ibm.com/support/pages/node/1146424"
        }
      ]
    }
  },
  "impact": {
    "baseMetricV2": {
      "acInsufInfo": false,
      "cvssV2": {
        "accessComplexity": "LOW",
        "accessVector": "NETWORK",
        "authentication": "SINGLE",
        "availabilityImpact": "NONE",
        "baseScore": 4,
        "confidentialityImpact": "PARTIAL",
        "integrityImpact": "NONE",
        "vectorString": "AV:N/AC:L/Au:S/C:P/I:N/A:N",
        "version": "2.0"
      },
      "exploitabilityScore": 8,
      "impactScore": 2.9,
      "obtainAllPrivilege": false,
      "obtainOtherPrivilege": false,
      "obtainUserPrivilege": false,
      "severity": "MEDIUM",
      "userInteractionRequired": false
    }
  },
  "lastModifiedDate": "2020-01-03T15:19Z",
  "publishedDate": "2019-12-30T16:15Z"
}