{
  "bugzilla": {
    "description": "\nCVE-2019-13139 docker: command injection due to a missing validation of the git ref command\n    ",
    "id": "1732627",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1732627"
  },
  "cvss3": {
    "cvss3_base_score": "6.7",
    "cvss3_scoring_vector": "CVSS:3.0/AV:L/AC:L/PR:H/UI:N/S:U/C:H/I:H/A:H",
    "status": "draft"
  },
  "cwe": "CWE-77",
  "details": [
    "\n** RESERVED ** This candidate has been reserved by an organization or individual that will use it when announcing a new security problem. When the candidate has been publicized, the details for this candidate will be provided.\n    "
  ],
  "name": "CVE-2019-13139",
  "package_state": [
    {
      "cpe": "cpe:/a:redhat:openshift:3.6",
      "fix_state": "New",
      "package_name": "docker",
      "product_name": "Red Hat OpenShift Container Platform 3.6"
    },
    {
      "cpe": "cpe:/a:redhat:openshift:3.7",
      "fix_state": "New",
      "package_name": "docker",
      "product_name": "Red Hat OpenShift Container Platform 3.7"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:7",
      "fix_state": "Affected",
      "package_name": "docker",
      "product_name": "Red Hat Enterprise Linux 7"
    }
  ],
  "public_date": "2019-03-26T00:00:00",
  "threat_severity": "Moderate",
  "upstream_fix": "docker engine 18.09.4"
}