{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat OpenShift Container Platform 4.1",
      "fix_state": "Under investigation",
      "package_name": "runc",
      "cpe": "cpe:/a:redhat:openshift:4.1"
    },
    {
      "product_name": "Red Hat OpenShift Container Platform 4.2",
      "fix_state": "Under investigation",
      "package_name": "runc",
      "cpe": "cpe:/a:redhat:openshift:4.2"
    },
    {
      "product_name": "Red Hat OpenShift Container Platform 4.3",
      "fix_state": "Under investigation",
      "package_name": "runc",
      "cpe": "cpe:/a:redhat:openshift:4.3"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Under investigation",
      "package_name": "docker",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Under investigation",
      "package_name": "runc",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Under investigation",
      "package_name": "container-tools:rhel8/runc",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Under investigation",
      "package_name": "container-tools:1.0/runc",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Under investigation",
      "package_name": "container-tools:2.0/runc",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2020-01-29T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2019-19921 runc: volume mount race condition with shared mounts leads to information leak/integrity manipulation",
    "id": "1796107",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1796107"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "7.0",
    "cvss3_scoring_vector": "CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:H/I:H/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-41",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2019-19921",
  "document_distribution": "",
  "details": [
    "No description is available for this CVE."
  ],
  "references": null
}