{
  "mitigation": "\nEnsure that debug logging is disabled and set to 0. This can be verified on the Bind server by the rndc status command.\n    ",
  "affected_release": [
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "release_date": "2019-01-29T00:00:00Z",
      "advisory": "RHSA-2019:0194",
      "package": "bind-9.9.4-73.el7_6",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    }
  ],
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 5",
      "fix_state": "Not affected",
      "package_name": "bind",
      "cpe": "cpe:/o:redhat:enterprise_linux:5"
    },
    {
      "product_name": "Red Hat Enterprise Linux 5",
      "fix_state": "Not affected",
      "package_name": "bind97",
      "cpe": "cpe:/o:redhat:enterprise_linux:5"
    },
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Not affected",
      "package_name": "bind",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "bind",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2018-12-18T13:59:00Z",
  "bugzilla": {
    "description": "\nCVE-2018-5742 bind: Crash from assertion error when debug log level is 10 and log entries meet buffer boundary\n    ",
    "id": "1655844",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1655844"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "5.9",
    "cvss3_scoring_vector": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
    "status": "verified"
  },
  "iava": "",
  "cwe": "CWE-400",
  "statement": "\n\n    ",
  "acknowledgement": "",
  "name": "CVE-2018-5742",
  "document_distribution": "",
  "details": [
    "\nNo description is available for this CVE.\n    "
  ],
  "references": [
    "\nhttps://www.openwall.com/lists/oss-security/2018/12/19/6\n    "
  ]
}