{
  "affected_release": [
    {
      "product_name": "Red Hat OpenShift Container Platform 3.11",
      "release_date": "2019-02-20T00:00:00Z",
      "advisory": "RHBA-2019:0326",
      "package": "haproxy-1.8.17-3.el7",
      "cpe": "cpe:/a:redhat:openshift:3.11::el7"
    },
    {
      "product_name": "Red Hat OpenShift Container Platform 3.9",
      "release_date": "2019-03-14T00:00:00Z",
      "advisory": "RHSA-2019:0547",
      "package": "haproxy-1.8.17-3.el7",
      "cpe": "cpe:/a:redhat:openshift:3.9::el7"
    },
    {
      "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux 7",
      "release_date": "2019-06-11T00:00:00Z",
      "advisory": "RHSA-2019:1436",
      "package": "rh-haproxy18-haproxy-1.8.17-1.el7",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3::el7"
    }
  ],
  "package_state": [
    {
      "product_name": "Red Hat OpenShift Container Platform 3.10",
      "fix_state": "Affected",
      "package_name": "haproxy",
      "cpe": "cpe:/a:redhat:openshift:3.10"
    },
    {
      "product_name": "Red Hat OpenShift Container Platform 3.7",
      "fix_state": "Affected",
      "package_name": "haproxy",
      "cpe": "cpe:/a:redhat:openshift:3.7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Not affected",
      "package_name": "haproxy",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Not affected",
      "package_name": "haproxy",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "haproxy",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2018-12-12T00:00:00Z",
  "bugzilla": {
    "description": "\nCVE-2018-20102 haproxy: Out-of-bounds read in dns.c:dns_validate_dns_response() allows for memory disclosure\n    ",
    "id": "1658874",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1658874"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "6.5",
    "cvss3_scoring_vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:L",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-125",
  "statement": "\nThis issue did not affect the versions of haproxy as shipped with Red Hat Enterprise Linux 6 and 7.\n\nRed Hat OpenShift Container Platform 3.10: \nThis vulnerability is currently targeted to be addressed in an upcoming release.\n\nRed Hat OpenShift Container Platform 3.7: \nThis vulnerability is currently targeted to be addressed in an upcoming release.\n    ",
  "acknowledgement": "",
  "name": "CVE-2018-20102",
  "document_distribution": "",
  "details": [
    "\nAn out-of-bounds read in dns_validate_dns_response in dns.c was discovered in HAProxy through 1.8.14. Due to a missing check when validating DNS responses, remote attackers might be able read the 16 bytes corresponding to an AAAA record from the non-initialized part of the buffer, possibly accessing anything that was left on the stack, or even past the end of the 8193-byte buffer, depending on the value of accepted_payload_size.\n    "
  ],
  "references": [
    "\nhttps://www.mail-archive.com/haproxy@formilux.org/msg32055.html\n    "
  ]
}