{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Ceph Storage 1.3",
      "fix_state": "Will not fix",
      "package_name": "PyYAML",
      "cpe": "cpe:/a:redhat:ceph_storage:1.3"
    },
    {
      "product_name": "Red Hat Enterprise MRG 2",
      "fix_state": "Will not fix",
      "package_name": "PyYAML",
      "cpe": "cpe:/a:redhat:enterprise_mrg:2"
    },
    {
      "product_name": "Red Hat Satellite 5",
      "fix_state": "Will not fix",
      "package_name": "PyYAML",
      "cpe": "cpe:/a:redhat:network_satellite:5"
    },
    {
      "product_name": "Red Hat OpenStack Platform 10 (Newton)",
      "fix_state": "Will not fix",
      "package_name": "PyYAML",
      "cpe": "cpe:/a:redhat:openstack:10"
    },
    {
      "product_name": "Red Hat OpenStack Platform 12 (Pike)",
      "fix_state": "Will not fix",
      "package_name": "PyYAML",
      "cpe": "cpe:/a:redhat:openstack:12"
    },
    {
      "product_name": "Red Hat OpenStack Platform 13 (Queens)",
      "fix_state": "Will not fix",
      "package_name": "PyYAML",
      "cpe": "cpe:/a:redhat:openstack:13"
    },
    {
      "product_name": "Red Hat OpenStack Platform 15 (Stein)",
      "fix_state": "Will not fix",
      "package_name": "PyYAML",
      "cpe": "cpe:/a:redhat:openstack:15"
    },
    {
      "product_name": "Red Hat Enterprise Linux OpenStack Platform 7 (Kilo)",
      "fix_state": "Will not fix",
      "package_name": "PyYAML",
      "cpe": "cpe:/a:redhat:openstack:7"
    },
    {
      "product_name": "Red Hat OpenStack Platform 8 (Liberty)",
      "fix_state": "Will not fix",
      "package_name": "PyYAML",
      "cpe": "cpe:/a:redhat:openstack:8"
    },
    {
      "product_name": "Red Hat OpenStack Platform 9 (Mitaka)",
      "fix_state": "Will not fix",
      "package_name": "PyYAML",
      "cpe": "cpe:/a:redhat:openstack:9"
    },
    {
      "product_name": "Red Hat Software Collections",
      "fix_state": "Will not fix",
      "package_name": "rh-python36-PyYAML",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3"
    },
    {
      "product_name": "Red Hat Software Collections",
      "fix_state": "Will not fix",
      "package_name": "rh-python35-PyYAML",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3"
    },
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Will not fix",
      "package_name": "PyYAML",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Will not fix",
      "package_name": "PyYAML",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Will not fix",
      "package_name": "PyYAML",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2018-06-27T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2017-18342 PyYAML: yaml.load() API could execute arbitrary code",
    "id": "1595743",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1595743"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "8.1",
    "cvss3_scoring_vector": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-20",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2017-18342",
  "document_distribution": "",
  "details": [
    "In PyYAML before 5.1, the yaml.load() API could execute arbitrary code if used with untrusted data. The load() function has been deprecated in version 5.1 and the 'UnsafeLoader' has been introduced for backward compatibility with the function."
  ],
  "references": null
}